### ISSUE TITLE
Add project on conda-forge?

### ISSUE THREAD

**Issue by erikmannerfelt** [rock-learning/pytransform3d#134]
We at [xdem](https://github.com/GlacioHack/xdem) are slowly preparing to put our package on conda-forge, and with `pytransform3d` as a dependency, I wonder if there's any plan to do this for `pytransform3d` as well?

Thanks in advance!
Erik

**Comment by AlexanderFabisch** [comment]
I don't know. How much additional effort would be required? Since pytransform3d is a pure Python project, is it even required?

**Comment by erikmannerfelt** [comment]
Thanks for the quick answer! According to the [conda-forge guidelines](https://conda-forge.org/docs/maintainer/adding_pkgs.html#avoid-external-dependencies), they want to avoid all non-conda-forge dependencies. Therefore, for us to upload xdem to conda-forge, we either need to modify our code to make `pytransform3d` entirely optional (which I prefer not to), or `pytransform3d` needs to be on conda-forge. 

I have some experience with conda recipes, so if you want, I can draft one and either help out or be in charge of publishing it on conda-forge.

I think it's a great addition to `pytransform3d` as well, as it may appeal to a larger audience!

**Comment by erikmannerfelt** [comment]
Here's a recipe for building it with conda:
```yml
{% set name = "pytransform3d" %}
{% set version = "1.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 4608079a30ef3f8e927f3b3aee7b58a1e47cdcd7c46be6d889d1cb0f82650baa

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - beautifulsoup4
    - lxml
    - matplotlib
    - numpy
    - pip
    - python
    - scipy
  run:
    - beautifulsoup4
    - lxml
    - matplotlib
    - numpy
    - python
    - scipy

test:
  imports:
    - pytransform3d

about:
  home: "https://github.com/rock-learning/pytransform3d"
  license: BSD
  license_family: BSD
  summary: "3D transformations for Python"
  doc_url: "https://rock-learning.github.io/pytransform3d/"
  dev_url: "https://github.com/rock-learning/pytransform3d"

extra:
  recipe-maintainers:
    - erikmannerfelt
```

I generated this from `conda skeleton pypi pytransform3d` with some minor "about" and "extra" modifications.

Validating it:
```bash
>>> conda-build .
>>> anaconda upload "$(conda-build --output .)"
>>> conda install -c eriksh pytransform3d -y
>>> python -c "import pytransform3d; print(pytransform3d.__version__)"
1.8
```
You should also be able to install it using the `eriksh` channel (my anaconda username).
